<a href="https://colab.research.google.com/github/huunhat3112006-sketch/AI/blob/main/01.python/BTTL/BaiTapTrenLop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=3
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)



8
-2
15
0.6


In [ ]:
value = "Hello World"
print(value[2:4])

ll


In [ ]:
value =" Hello World "
print(f"{value.strip().upper()}")
print(f"{value.strip().lower()}")
print(f"{value.strip().replace('H','J')}")


HELLO WORLD
hello world
Jello World


In [ ]:
a=5
b=3
if a>b:
  print("Hello World")

Hello World


In [ ]:
a=5
b=3
if a == b:
  print("Yes")
else:
  print("No")

No


In [ ]:
a=5
b=3
if a==b:
  print(1)
elif a>b:
  print(2)
else:
  print(3)

2


In [ ]:
a=b=c=d=3
if a==b and c==d:
  print("Hello World!")


Hello World!


In [ ]:
a=b=3
c=5
d=4
if a==b or c==d:
  print("Hello World!")

Hello World!


In [ ]:
a=5
b=3
result = "Yes" if a>b else "No"
print(result)

Yes


In [ ]:
a=3
b=5
print("A") if a>b else print("=")if a==b else print("B")

B


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
arr = a % 2 ==0
b = a[arr]
print(b)


[2 4 6]


In [ ]:
tong =0
for i in range(0,999):
  if i%3==0 or i%5==0:
    tong+=i
print(tong)

232169


In [ ]:
import numpy as np
a = np.array([3,9,1,4])
b=np.array([2,7,4,3,2,8])
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a)>len(b) else b
for i in range(min):
  c[i] = a[i]+b[i]
print(c)

[ 5 16  5  7  2  8]


In [ ]:
import numpy as np
m=int(input("Nhập số dòng m:"))
n=int(input("Nhập số cột n:"))
a = np.random.randint(0,20,size=(m,n))
print(a)
k=int(input("Nhập số dòng k muốn xuất:"))
print(a[k-1,:])
h=int(input("Nhập số cột k muốn xuất:"))
print(a[:,h-1])

max_dong = -np.inf
dia_chi_dong = -1
for i in range(m):
  dong = a[i,:]
  tong_dong = np.sum(dong)
  if tong_dong > max_dong and tong_dong>45:
    max_dong = tong_dong
    dia_chi_dong = i

if(dia_chi_dong!=-1):
  print(f"Tổng dòng lớn nhất và lớn hơn 45 dòng {dia_chi_dong+1}: {max_dong}")
else:
   print(f"Không có dòng nào lớn hơn 45")

min_cot = np.inf
dia_chi_cot = -1
for i in range(n):
  cot= a[:,i]
  tich_cot = np.prod(cot)
  if tich_cot < min_cot:
    min_cot = tich_cot
    dia_chi_cot = i
print(f"cột có tích nhỏ nhất là cột {dia_chi_cot+1}: {min_cot}")
for i in range(m):
  for j in range(n):
    if i%2==0 and j%2!=0:
      print(f"Các phần tử dòng chẵn cột lẻ {a[i,j]}")

phan_tu_chan =[]
for i in range(m):
  for j in range(n):
    if (i+1) %2!=0:
      if a[i,j] % 2 ==0:
       phan_tu_chan.append(a[i,j])
trung_binh = np.mean(phan_tu_chan)
print(f"Trung bình cộng các phần tử chẵn thuộc dòng lẻ: {trung_binh}")

ma_tran_bien=np.ones(a.shape,dtype=bool)
ma_tran_bien[1:-1,1:-1]=False
phan_tu_bien = a[ma_tran_bien]
if phan_tu_bien.size>0:
  tb_bien = np.mean(phan_tu_bien)
  print(f"Trung bình cộng các phần tử nằm trên biên là: {tb_bien}")
phan_tu_loi=a[1:-1,1:-1]
if phan_tu_loi.size>0:
  tich_loi = np.prod(phan_tu_loi)
  tb_tich_loi = tich_loi**(1/phan_tu_loi.size)
  print(f"Tích các phần tử bên trong:{tich_loi}")
  print(f"Trung bình cộng các phần tử bên trong: {tb_tich_loi:.4f}")
else:
  print("Ma trận quá nhỏ, không có phần tử bên trong")


Nhập số dòng m:4
Nhập số cột n:4
[[ 5 18  6  2]
 [13 12  5 11]
 [ 4 10  2  1]
 [15  0 15 10]]
Nhập số dòng k muốn xuất:2
[13 12  5 11]
Nhập số cột k muốn xuất:3
[ 6  5  2 15]
Không có dòng nào lớn hơn 45
cột có tích nhỏ nhất là cột 2: 0
Các phần tử dòng chẵn cột lẻ 18
Các phần tử dòng chẵn cột lẻ 2
Các phần tử dòng chẵn cột lẻ 10
Các phần tử dòng chẵn cột lẻ 1
Trung bình cộng các phần tử chẵn thuộc dòng lẻ: 7.0
Trung bình cộng các phần tử nằm trên biên là: 8.333333333333334
Tích các phần tử bên trong:1200
Trung bình cộng các phần tử bên trong: 5.8857


In [ ]:
import datetime as date
class SinhVien:
  def __init__(self,masv,ten,namsinh,diemtb) :
     self.masv=masv
     self.ten = ten
     self.namsinh = namsinh
     self.diemtb = diemtb
  def inThongTin(self):
    print(f"{self.masv}|{self.ten}|{self.namsinh}|{self.diemtb}")
n=int(input("Nhập số sinh viên cần tạo:"))
a=[]
def tao_danh_sach_sv():
  for i in range(n):
    masv=input("Nhập mã sinh viên:")
    ten=input("Nhập tên sinh viên:")
    namsinh=int(input("Nhập năm sinh:"))
    diemtb=float(input("Nhập điểm trung bình:"))
    sv=SinhVien(masv,ten,namsinh,diemtb)
    a.append(sv)
def kiem_tra_sv():
  for i in a:
    if i.diemtb >=5:
      print(f"Sinh viên {i.ten} đủ điều kiện lên lớp")
    else :
      print(f"Sinh viên {i.ten} ko đủ điều kiện lên lớp")
ngay_hien_tai = date.datetime.now()
def kiem_tra_tuoi_sv():
  for i in a:
    tuoi = ngay_hien_tai.year - i.namsinh
    if tuoi >=20:
        i.inThongTin()

def dem_sv_dai_hoc():
  count=0
  for i in a:
    if len(i.masv) > 3 and i.masv[2] =="D" and i.masv[3] =="H":
      count+=1
  print(f"Số sinh viên hệ đại học {count}")
def dem_sv_ten_lan():
  count =0
  for i in a:
    if "Lan"in i.ten:
      count+=1
  print(f"Số sinh viên tên Lan là {count}")
def dem_sv_ho_phan():
  count = 0
  for i in a:
    if i.ten.startswith("Phan"):
      count+=1
  print(f"Số sinh viên họ Phan là {count}")
tao_danh_sach_sv()
kiem_tra_sv()
kiem_tra_tuoi_sv()
dem_sv_dai_hoc()
dem_sv_ten_lan()
dem_sv_ho_phan()

Nhập số sinh viên cần tạo:3
Nhập mã sinh viên:02DH0001
Nhập tên sinh viên:Nguyen Huu Nhat
Nhập năm sinh:2006
Nhập điểm trung bình:8.5
Nhập mã sinh viên:SV001
Nhập tên sinh viên:Nguyen Thi Lan
Nhập năm sinh:2008
Nhập điểm trung bình:4
Nhập mã sinh viên:02DH0002
Nhập tên sinh viên:Phan Hong Lan
Nhập năm sinh:2004
Nhập điểm trung bình:6.5
Sinh viên Nguyen Huu Nhat đủ điều kiện lên lớp
Sinh viên Nguyen Thi Lan ko đủ điều kiện lên lớp
Sinh viên Phan Hong Lan đủ điều kiện lên lớp
02DH0001|Nguyen Huu Nhat|2006|8.5
02DH0002|Phan Hong Lan|2004|6.5
Số sinh viên hệ đại học 2
Số sinh viên tên Lan là 2
Số sinh viên họ Phan là 1
